import { BookOpen, Check, HeartHandshake, Laptop, Lightbulb, ShieldCheck, Stethoscope, Users } from "lucide-react"

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Button } from "@/components/ui/button"

const areas = [
  [BookOpen, "Teaching and Academic", "Help shape learning through instruction, academic guidance, and scholarship."],
  [Users, "Administration and Professional Services", "Support the university through thoughtful and dependable professional practice."],
  [Stethoscope, "Healthcare and Clinical Services", "Contribute professional care within university health and clinical settings."],
  [Lightbulb, "Research and Innovation", "Advance inquiry, applied knowledge, and responsible innovation."],
  [Laptop, "Information Technology", "Strengthen teaching and operations through secure and effective technology."],
  [HeartHandshake, "Student and Support Services", "Help create a supportive, responsive environment for the university community."],
] as const

const values = [
  ["Excellence in Education", "Contribute your expertise to a university committed to high standards in teaching, research, professional service, and institutional practice."],
  ["Service With Compassion", "Work within a community that values dignity, responsibility, collaboration, and care for others."],
  ["Professional Development", "Grow through meaningful responsibilities, collegial learning, and opportunities for continuous professional formation."],
  ["Collaborative Community", "Join educators, administrators, researchers, healthcare professionals, and support personnel working toward a shared institutional mission."],
] as const

const steps = [
  ["Explore Openings", "Review available positions and identify a role that matches your education, experience, and professional interests."],
  ["Review Qualifications", "Read the position description, minimum qualifications, required credentials, and application deadline carefully."],
  ["Complete Your Profile", "Provide accurate personal, educational, employment, and professional information in your applicant profile."],
  ["Submit Requirements", "Upload the documents required for the selected vacancy and review your application before final submission."],
  ["Track Your Application", "Use the applicant portal to view official updates, additional requirements, and recruitment schedules."],
] as const

const faqs = [
  ["How do I apply for a position?", "Select an open vacancy, review its qualifications and document requirements, then sign in or create an applicant profile to complete and submit your application."],
  ["Can I apply for more than one opening?", "You may apply for more than one vacancy when your qualifications match the requirements. A separate application may be required for each position."],
  ["What documents should I prepare?", "Common documents include an application letter, résumé or curriculum vitae, Transcript of Records, and diploma. Licenses, certificates, and other supporting documents may be required for specific positions."],
  ["Can I update my application after submission?", "You may update your reusable applicant profile, but information already submitted for a particular vacancy may be locked. Follow any official request from the Human Resource Management Office for corrections or additional documents."],
  ["How will I know whether my application has progressed?", "Official updates may appear in your applicant dashboard and may also be sent to your registered email address. Keep your contact information current and monitor official SPUP channels. Submission does not guarantee an interview or employment."],
  ["Who should I contact if I experience a technical issue?", "Use only a verified support channel published by St. Paul University Philippines. Contact details should be confirmed by SPUP Human Resources before this prototype is placed in production."],
] as const

function SectionHeading({ eyebrow, title, description }: { eyebrow?: string; title: string; description?: string }) {
  return <header className="max-w-3xl">{eyebrow ? <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#167654]">{eyebrow}</p> : null}<h2 className="mt-3 font-serif text-3xl font-semibold leading-tight text-[#063d29] sm:text-4xl">{title}</h2>{description ? <p className="mt-4 text-base leading-7 text-[#66716a]">{description}</p> : null}</header>
}

export function CareersInformation() {
  return <>
    <section id="employment-areas" className="border-t border-[#e4e9e6] bg-[#fffefa] py-14 sm:py-18 lg:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><SectionHeading title="Opportunities Across the University" description="Explore the professional areas that contribute to SPUP’s academic mission and daily university life." /><div className="mt-8 grid gap-px overflow-hidden rounded-xl border border-[#dce3de] bg-[#dce3de] sm:grid-cols-2 lg:grid-cols-3">{areas.map(([Icon, title, copy]) => <article key={title} className="bg-white p-6"><Icon className="size-6 text-[#b78a28]" aria-hidden="true" /><h3 className="mt-4 font-serif text-xl font-semibold text-[#063d29]">{title}</h3><p className="mt-2 leading-7 text-[#66716a]">{copy}</p></article>)}</div></div></section>
    <section id="why-spup" className="scroll-mt-28 bg-[#eef5f0] py-14 sm:py-18 lg:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><SectionHeading eyebrow="A Paulinian workplace" title="A Career Grounded in Purpose" description="At SPUP, professional work contributes to a larger educational mission. Every role supports the formation of learners, the advancement of knowledge, and meaningful service to communities." /><div className="mt-8 grid gap-7 md:grid-cols-2">{values.map(([title, copy], index) => <article key={title} className="border-t border-[#b5c9bc] pt-5"><span className="text-sm font-semibold text-[#b78a28]">0{index + 1}</span><h3 className="mt-2 font-serif text-xl font-semibold text-[#063d29]">{title}</h3><p className="mt-2 leading-7 text-[#536159]">{copy}</p></article>)}</div></div></section>
    <aside className="bg-[#063d29] py-14 text-white sm:py-18"><div className="mx-auto max-w-4xl px-5 text-center sm:px-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#e9cf88]">The Paulinian Commitment</p><blockquote className="mt-5 font-serif text-2xl leading-relaxed sm:text-3xl">“Your work at SPUP becomes part of a wider mission that forms persons, strengthens communities, and advances knowledge through service.”</blockquote></div></aside>
    <section id="application-process" className="scroll-mt-28 bg-white py-14 sm:py-18 lg:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><SectionHeading eyebrow="How to apply" title="Your Application Journey" description="Follow a clear and secure process from vacancy selection to recruitment evaluation." /><ol className="relative mt-10 grid gap-7 lg:grid-cols-5 lg:gap-5">{steps.map(([title, copy], index) => <li key={title} className="relative border-l border-[#c7d3cc] pb-3 pl-8 lg:border-l-0 lg:border-t lg:pl-0 lg:pt-8"><span className="absolute -left-[1px] top-0 flex size-11 -translate-x-1/2 items-center justify-center rounded-full border border-[#9db7a7] bg-white font-semibold text-[#07543a] lg:left-0 lg:-top-[1px] lg:-translate-y-1/2 lg:translate-x-0">{index + 1}</span><h3 className="font-serif text-lg font-semibold text-[#063d29] lg:mt-2">{title}</h3><p className="mt-2 text-sm leading-6 text-[#66716a]">{copy}</p></li>)}</ol><Button asChild className="mt-8 min-h-12 bg-[#07543a] text-white"><a href="/login?returnTo=%2Ftest-careers">Create applicant profile</a></Button></div></section>
    <section id="application-requirements" className="scroll-mt-28 bg-[#faf8f1] py-14 sm:py-18 lg:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><SectionHeading title="Prepare Your Application Documents" description="Requirements vary by position. Review the specific vacancy carefully before submitting your application." /><div className="mt-8 grid gap-8 lg:grid-cols-2">{[["Commonly Required", ["Application letter", "Updated résumé or curriculum vitae", "Transcript of Records", "Diploma"]], ["When Applicable", ["Valid PRC identification", "Certificate of Employment", "Latest performance rating", "Certificates of training", "Professional eligibility documents", "Other credentials requested for the vacancy"]]].map(([title, items]) => <div key={title as string}><h3 className="font-serif text-xl font-semibold text-[#063d29]">{title as string}</h3><ul className="mt-4 divide-y divide-[#dce3de] border-y border-[#dce3de]">{(items as string[]).map((item) => <li key={item} className="flex min-h-12 items-center gap-3 py-3"><Check className="size-4 shrink-0 text-[#167654]" aria-hidden="true" />{item}</li>)}</ul></div>)}</div><p className="mt-7 max-w-3xl border-l-2 border-[#b78a28] pl-4 text-sm leading-6 text-[#536159]">The final list of required documents is determined by the vacancy. Only submit documents requested through official SPUP recruitment channels.</p></div></section>
    <section className="bg-white py-12"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="flex gap-4 rounded-xl border border-[#cfbf91] bg-[#faf4e3] p-5 sm:p-7"><ShieldCheck className="mt-1 size-7 shrink-0 text-[#07543a]" aria-hidden="true" /><div><h2 className="font-serif text-xl font-semibold text-[#063d29]">Apply Only Through Official SPUP Channels</h2><p className="mt-2 leading-7 text-[#536159]">St. Paul University Philippines does not authorize unofficial representatives to collect applicant information or recruitment payments. Protect your personal information and use only this portal and verified SPUP contact channels.</p></div></div></div></section>
    <section id="faqs" className="scroll-mt-28 bg-[#eef5f0] py-14 sm:py-18 lg:py-20"><div className="mx-auto max-w-4xl px-5 sm:px-8"><SectionHeading eyebrow="Applicant guidance" title="Frequently Asked Questions" /><Accordion type="single" collapsible className="mt-7 rounded-xl border border-[#d3ded7] bg-white px-5 sm:px-7">{faqs.map(([question, answer], index) => <AccordionItem key={question} value={`faq-${index}`}><AccordionTrigger className="min-h-14 text-left text-base font-semibold text-[#26342c] hover:text-[#07543a]">{question}</AccordionTrigger><AccordionContent className="pb-5 text-base leading-7 text-[#66716a]">{answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <section className="bg-[#063d29] py-14 text-white sm:py-18"><div className="mx-auto max-w-4xl px-5 text-center sm:px-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#e9cf88]">Begin your Paulinian journey</p><h2 className="mt-4 font-serif text-3xl font-semibold leading-tight sm:text-4xl">Bring Your Knowledge, Experience, and Commitment to SPUP.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-white/75">Review current vacancies and apply through the official SPUP recruitment portal.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Button asChild size="lg" className="min-h-12 bg-white text-[#063d29] hover:bg-[#f4e8c5]"><a href="#openings">Browse job openings</a></Button><Button asChild size="lg" variant="outline" className="min-h-12 border-white/50 bg-transparent text-white hover:bg-white/10 hover:text-white"><a href="/login?returnTo=%2Ftest-careers">Create applicant profile</a></Button></div></div></section>
  </>
}
