import Image from "next/image"
import Link from "next/link"

const groups = [
  ["Applicants", [["Job Openings", "#openings"], ["Application Process", "#application-process"], ["Application Requirements", "#application-requirements"], ["Frequently Asked Questions", "#faqs"]]],
  ["About Employment", [["Why Work at SPUP", "#why-spup"], ["Employment Areas", "#employment-areas"], ["Recruitment Notice", "#application-requirements"]]],
] as const

export function CareersFooter() {
  return <footer className="border-t border-[#dce3de] bg-[#fffefa]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:px-8 md:grid-cols-2 lg:grid-cols-4 lg:px-12"><div className="md:col-span-2 lg:col-span-2"><div className="flex items-center gap-3"><Image src="/SPUP-final-logo.png" alt="" width={52} height={52} className="size-12 object-contain" /><div><p className="font-serif text-xl font-semibold text-[#063d29]">SPUP Careers</p><p className="text-sm text-[#66716a]">St. Paul University Philippines Recruitment Portal</p></div></div><p className="mt-5 max-w-md leading-7 text-[#66716a]">The official platform for employment opportunities and applicant services at St. Paul University Philippines.</p></div>{groups.map(([heading, links]) => <nav key={heading} aria-label={heading}><h2 className="font-semibold text-[#26342c]">{heading}</h2><ul className="mt-4 space-y-2">{links.map(([label, href]) => <li key={href}><a href={href} className="inline-flex min-h-11 items-center text-sm text-[#66716a] hover:text-[#07543a] hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#167654]">{label}</a></li>)}</ul></nav>)}<nav aria-label="Applicant support"><h2 className="font-semibold text-[#26342c]">Support</h2><ul className="mt-4 space-y-2"><li><Link href="/login?returnTo=%2Ftest-careers" className="inline-flex min-h-11 items-center text-sm text-[#66716a] hover:text-[#07543a] hover:underline">Applicant sign in</Link></li><li className="text-sm leading-6 text-[#66716a]">HR and technical support contact details pending institutional verification.</li></ul></nav></div><div className="border-t border-[#dce3de]"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-6 text-sm text-[#66716a] sm:px-8 md:flex-row md:items-center md:justify-between lg:px-12"><p>© 2026 St. Paul University Philippines. All rights reserved.</p><a href="#main-content" className="min-h-11 self-start py-3 font-medium text-[#07543a] hover:underline">Back to top</a></div></div></footer>
}
